export interface Product {
  id: string;
  linkProduto: string;
  imgSrc: string;
  imgSrc2: string;
  caption: string;
  categorias: string;
  caption2: string;
  price: string;
  promotion: string;
  parcelasValor: string;
  produtoTag: string;
}

export const productsData: Product[] = [
  {
    id: "52",
    linkProduto: "https://allinbrasil.com.br/loja/index.php?route=product/product&product_id=52",
    imgSrc: "https://s3-sa-east-1.amazonaws.com/public-http-cache/UploadArquivo/Arquivos/all_in_esp_br/loja/image/cache/catalog-5503-img-4850-800x945.jpeg",
    imgSrc2: "",
    caption: "Bone All-In Claro",
    categorias: "Acessórios",
    caption2: "BONE ALL-IN CLARO",
    price: "R$ 79,80",
    promotion: "",
    parcelasValor: "5x de  R$ 15,96",
    produtoTag: ""
  },
  {
    id: "303",
    linkProduto: "https://allinbrasil.com.br/loja/index.php?route=product/product&product_id=303",
    imgSrc: "https://s3-sa-east-1.amazonaws.com/public-http-cache/UploadArquivo/Arquivos/all_in_esp_br/loja/image/cache/catalog-2127-moleskini-800x945.png",
    imgSrc2: "",
    caption: "Caderneta All-In *R$ 59,00*",
    categorias: "Acessórios",
    caption2: "CADERNETA",
    price: "R$ 118,00",
    promotion: "",
    parcelasValor: "5x de  R$ 23,60",
    produtoTag: ""
  },
  {
    id: "339",
    linkProduto: "https://allinbrasil.com.br/loja/index.php?route=product/product&product_id=339",
    imgSrc: "https://s3-sa-east-1.amazonaws.com/public-http-cache/UploadArquivo/Arquivos/all_in_esp_br/loja/image/cache/catalog-8440-begee-800x945.jpg",
    imgSrc2: "",
    caption: "Faixa De Cabeça Bege",
    categorias: "Acessórios",
    caption2: "FAIXA DE CABEÇA BEGEA Sense Band émais do que umacessório, é um lembrete diário para cuidar de simesm...",
    price: "R$ 59,99",
    promotion: "",
    parcelasValor: "5x de  R$ 11,99",
    produtoTag: ""
  },
  {
    id: "337",
    linkProduto: "https://allinbrasil.com.br/loja/index.php?route=product/product&product_id=337",
    imgSrc: "https://s3-sa-east-1.amazonaws.com/public-http-cache/UploadArquivo/Arquivos/all_in_esp_br/loja/image/cache/catalog-1427-brancaa-800x945.jpg",
    imgSrc2: "",
    caption: "Faixa De Cabeça Branca",
    categorias: "Acessórios",
    caption2: "FAIXA DE CABEÇA BRANCAA Sense Band émais do que umacessório, é um\nlembrete diário para cuidar de sime...",
    price: "R$ 59,99",
    promotion: "",
    parcelasValor: "5x de  R$ 11,99",
    produtoTag: ""
  },
  {
    id: "338",
    linkProduto: "https://allinbrasil.com.br/loja/index.php?route=product/product&product_id=338",
    imgSrc: "https://s3-sa-east-1.amazonaws.com/public-http-cache/UploadArquivo/Arquivos/all_in_esp_br/loja/image/cache/catalog-2282-pretaa-800x945.jpg",
    imgSrc2: "",
    caption: "Faixa De Cabeça Preta",
    categorias: "Acessórios",
    caption2: "FAIXA DE CABEÇA PRETAA Sense Band émais do que umacessório, é um lembrete diário para cuidar de simesm...",
    price: "R$ 59,99",
    promotion: "",
    parcelasValor: "5x de  R$ 11,99",
    produtoTag: ""
  },
  {
    id: "53",
    linkProduto: "https://allinbrasil.com.br/loja/index.php?route=product/product&product_id=53",
    imgSrc: "https://s3-sa-east-1.amazonaws.com/public-http-cache/UploadArquivo/Arquivos/all_in_esp_br/loja/image/cache/catalog-6952-foto-palmilha-800x945.jpg",
    imgSrc2: "https://s3-sa-east-1.amazonaws.com/public-http-cache/UploadArquivo/Arquivos/all_in_esp_br/loja/image/cache/catalog-6270-palmilha-800x945.jpeg",
    caption: "Palmilha Confortplus",
    categorias: "Acessórios",
    caption2: "PALMILHA CONFORTPLUS",
    price: "R$ 69,00",
    promotion: "",
    parcelasValor: "5x de  R$ 13,80",
    produtoTag: ""
  },
  {
    id: "340",
    linkProduto: "https://allinbrasil.com.br/loja/index.php?route=product/product&product_id=340",
    imgSrc: "https://s3-sa-east-1.amazonaws.com/public-http-cache/UploadArquivo/Arquivos/all_in_esp_br/loja/image/cache/catalog-7978-cloud-chinelo-azul-1-800x945.png",
    imgSrc2: "https://s3-sa-east-1.amazonaws.com/public-http-cache/UploadArquivo/Arquivos/all_in_esp_br/loja/image/cache/catalog-4817-cloud-chinelo-azul-3-800x945.png",
    caption: "Cloud Chinelo Azul Feminino",
    categorias: "Chinelos",
    caption2: "CLOUD CHINELO AZUL FEMININO",
    price: "R$ 199,00",
    promotion: "",
    parcelasValor: "5x de  R$ 39,80",
    produtoTag: "Limitado"
  },
  {
    id: "309",
    linkProduto: "https://allinbrasil.com.br/loja/index.php?route=product/product&product_id=309",
    imgSrc: "https://s3-sa-east-1.amazonaws.com/public-http-cache/UploadArquivo/Arquivos/all_in_esp_br/loja/image/cache/catalog-2559-cloud-chinelo-preto-1-800x945.png",
    imgSrc2: "https://s3-sa-east-1.amazonaws.com/public-http-cache/UploadArquivo/Arquivos/all_in_esp_br/loja/image/cache/catalog-5240-cloud-chinelo-preto-2-800x945.png",
    caption: "Cloud Chinelo Preto Unissex",
    categorias: "Chinelos",
    caption2: "Cloud Chinelo Unisex - Conforto, Estilo e Magnoterapia com E.V.A de Alta QualidadeO Cloud ...",
    price: "R$ 199,00",
    promotion: "",
    parcelasValor: "5x de  R$ 39,80",
    produtoTag: ""
  },
  {
    id: "308",
    linkProduto: "https://allinbrasil.com.br/loja/index.php?route=product/product&product_id=308",
    imgSrc: "https://s3-sa-east-1.amazonaws.com/public-http-cache/UploadArquivo/Arquivos/all_in_esp_br/loja/image/cache/catalog-2342-cloud-chinelo-rose-1-800x945.png",
    imgSrc2: "https://s3-sa-east-1.amazonaws.com/public-http-cache/UploadArquivo/Arquivos/all_in_esp_br/loja/image/cache/catalog-1524-cloud-chinelo-rose-4-800x945.png",
    caption: "Cloud Chinelo Rose Feminino",
    categorias: "Chinelos",
    caption2: "Cloud Chinelo Rose Feminino - Conforto, Estilo e Magnoterapia com E.V.A de Alta Qualidade    O...",
    price: "R$ 199,00",
    promotion: "",
    parcelasValor: "5x de  R$ 39,80",
    produtoTag: ""
  },
  {
    id: "341",
    linkProduto: "https://allinbrasil.com.br/loja/index.php?route=product/product&product_id=341",
    imgSrc: "https://s3-sa-east-1.amazonaws.com/public-http-cache/UploadArquivo/Arquivos/all_in_esp_br/loja/image/cache/catalog-6742-cloud-tiras-preto-1-800x945.png",
    imgSrc2: "https://s3-sa-east-1.amazonaws.com/public-http-cache/UploadArquivo/Arquivos/all_in_esp_br/loja/image/cache/catalog-3072-cloud-tiras-preto-2-800x945.png",
    caption: "Cloud Chinelo Tiras Preto Feminino",
    categorias: "Chinelos",
    caption2: "Cloud Chinelo Preto Feminino - Conforto, Estilo e Magnoterapia com E.V.A de Alta QualidadeO Cloud ...",
    price: "R$ 199,00",
    promotion: "",
    parcelasValor: "5x de  R$ 39,80",
    produtoTag: ""
  },
  {
    id: "329",
    linkProduto: "https://allinbrasil.com.br/loja/index.php?route=product/product&product_id=329",
    imgSrc: "https://s3-sa-east-1.amazonaws.com/public-http-cache/UploadArquivo/Arquivos/all_in_esp_br/loja/image/cache/catalog-6027-imagem-do-whatsapp-de-2024-09-23-as-151917-74f0e5c7-800x945.jpg",
    imgSrc2: "",
    caption: "Legging Emana G",
    categorias: "Mantas",
    caption2: "Legging Emana G - Tecnologia Avançada para Bem-Estar e Performance Esportiva | All-in    A ...",
    price: "R$ 349,00",
    promotion: "",
    parcelasValor: "5x de  R$ 69,80",
    produtoTag: ""
  },
  {
    id: "324",
    linkProduto: "https://allinbrasil.com.br/loja/index.php?route=product/product&product_id=324",
    imgSrc: "https://s3-sa-east-1.amazonaws.com/public-http-cache/UploadArquivo/Arquivos/all_in_esp_br/loja/image/cache/catalog-5793-imagem-do-whatsapp-de-2024-09-02-as-151105-49216b9a-800x945.jpg",
    imgSrc2: "",
    caption: "Manta Ativa Casal",
    categorias: "Mantas",
    caption2: "Manta Ativa Multifuncional Casal 140x190 - Tecnologia Infravermelho Longo Permanente (FIR...",
    price: "R$ 590,00",
    promotion: "",
    parcelasValor: "5x de  R$ 118,00",
    produtoTag: ""
  },
  {
    id: "326",
    linkProduto: "https://allinbrasil.com.br/loja/index.php?route=product/product&product_id=326",
    imgSrc: "https://s3-sa-east-1.amazonaws.com/public-http-cache/UploadArquivo/Arquivos/all_in_esp_br/loja/image/cache/catalog-5793-imagem-do-whatsapp-de-2024-09-02-as-151105-49216b9a-800x945.jpg",
    imgSrc2: "",
    caption: "Manta Ativa King",
    categorias: "Mantas",
    caption2: "Manta Ativa Multifuncional King 193x203 - Tecnologia Infravermelho Longo Permanente (FIR...",
    price: "R$ 766,00",
    promotion: "",
    parcelasValor: "5x de  R$ 153,20",
    produtoTag: ""
  },
  {
    id: "325",
    linkProduto: "https://allinbrasil.com.br/loja/index.php?route=product/product&product_id=325",
    imgSrc: "https://s3-sa-east-1.amazonaws.com/public-http-cache/UploadArquivo/Arquivos/all_in_esp_br/loja/image/cache/catalog-5793-imagem-do-whatsapp-de-2024-09-02-as-151105-49216b9a-800x945.jpg",
    imgSrc2: "",
    caption: "Manta Ativa Queen",
    categorias: "Mantas",
    caption2: "Manta Ativa Multifuncional Queen 160x200 - Tecnologia Infravermelho Longo Permanente (FIR...",
    price: "R$ 678,00",
    promotion: "",
    parcelasValor: "5x de  R$ 135,60",
    produtoTag: ""
  },
  {
    id: "323",
    linkProduto: "https://allinbrasil.com.br/loja/index.php?route=product/product&product_id=323",
    imgSrc: "https://s3-sa-east-1.amazonaws.com/public-http-cache/UploadArquivo/Arquivos/all_in_esp_br/loja/image/cache/catalog-5793-imagem-do-whatsapp-de-2024-09-02-as-151105-49216b9a-800x945.jpg",
    imgSrc2: "",
    caption: "Manta Ativa Solteiro",
    categorias: "Mantas",
    caption2: "Manta Ativa Multifuncional Solteiro 090x190 - Tecnologia Infravermelho Longo Permanente (FIR...",
    price: "R$ 438,00",
    promotion: "",
    parcelasValor: "5x de  R$ 87,60",
    produtoTag: ""
  },
  {
    id: "328",
    linkProduto: "https://allinbrasil.com.br/loja/index.php?route=product/product&product_id=328",
    imgSrc: "https://s3-sa-east-1.amazonaws.com/public-http-cache/UploadArquivo/Arquivos/all_in_esp_br/loja/image/cache/catalog-9297-legging-emana-3-800x945.png",
    imgSrc2: "https://s3-sa-east-1.amazonaws.com/public-http-cache/UploadArquivo/Arquivos/all_in_esp_br/loja/image/cache/catalog-9311-legging-emana-1-800x945.png",
    caption: "Legging Emana M",
    categorias: "Meias",
    caption2: "Legging Emana M - Tecnologia Inteligente para Bem-Estar e Performance Esportiva | All-in    A...",
    price: "R$ 349,00",
    promotion: "",
    parcelasValor: "5x de  R$ 69,80",
    produtoTag: ""
  },
  {
    id: "327",
    linkProduto: "https://allinbrasil.com.br/loja/index.php?route=product/product&product_id=327",
    imgSrc: "https://s3-sa-east-1.amazonaws.com/public-http-cache/UploadArquivo/Arquivos/all_in_esp_br/loja/image/cache/catalog-9311-legging-emana-1-800x945.png",
    imgSrc2: "https://s3-sa-east-1.amazonaws.com/public-http-cache/UploadArquivo/Arquivos/all_in_esp_br/loja/image/cache/catalog-9297-legging-emana-3-800x945.png",
    caption: "Legging Emana P",
    categorias: "Meias",
    caption2: "Legging Emana P - Tecnologia Inteligente para Bem-Estar e Performance Esportiva | All-in    A...",
    price: "R$ 349,00",
    promotion: "",
    parcelasValor: "5x de  R$ 69,80",
    produtoTag: ""
  },
  {
    id: "315",
    linkProduto: "https://allinbrasil.com.br/loja/index.php?route=product/product&product_id=315",
    imgSrc: "https://s3-sa-east-1.amazonaws.com/public-http-cache/UploadArquivo/Arquivos/all_in_esp_br/loja/image/cache/catalog-3610-meias-brancas-alta-800x945.png",
    imgSrc2: "",
    caption: "Meia All-In Emana Branca Cano Curto",
    categorias: "Meias",
    caption2: "Meia All-in Emana Branca Cano Curto - Conforto, Tecnologia e Bem-Estar | All-in    A Meia...",
    price: "R$ 129,00",
    promotion: "",
    parcelasValor: "5x de  R$ 25,80",
    produtoTag: ""
  },
  {
    id: "317",
    linkProduto: "https://allinbrasil.com.br/loja/index.php?route=product/product&product_id=317",
    imgSrc: "https://s3-sa-east-1.amazonaws.com/public-http-cache/UploadArquivo/Arquivos/all_in_esp_br/loja/image/cache/catalog-4013-meias-brancas-800x945.png",
    imgSrc2: "",
    caption: "Meia All-In Emana Branca Invisível",
    categorias: "Meias",
    caption2: "Meia All-in Emana Branca Invisível - Conforto e Tecnologia | All-in    A Meia All-in Emana ...",
    price: "R$ 99,90",
    promotion: "",
    parcelasValor: "5x de  R$ 19,98",
    produtoTag: ""
  },
  {
    id: "314",
    linkProduto: "https://allinbrasil.com.br/loja/index.php?route=product/product&product_id=314",
    imgSrc: "https://s3-sa-east-1.amazonaws.com/public-http-cache/UploadArquivo/Arquivos/all_in_esp_br/loja/image/cache/catalog-2216-meias-preta-800x945.png",
    imgSrc2: "",
    caption: "Meia All-In Emana Preta Cano Curto",
    categorias: "Meias",
    caption2: "Meia All-in Emana Preta Cano Curto - Tecnologia Emana para Bem-Estar e Conforto | All-in    A...",
    price: "R$ 129,00",
    promotion: "",
    parcelasValor: "5x de  R$ 25,80",
    produtoTag: ""
  },
  {
    id: "316",
    linkProduto: "https://allinbrasil.com.br/loja/index.php?route=product/product&product_id=316",
    imgSrc: "https://s3-sa-east-1.amazonaws.com/public-http-cache/UploadArquivo/Arquivos/all_in_esp_br/loja/image/cache/catalog-9194-meias-curtas-preta-800x945.png",
    imgSrc2: "",
    caption: "Meia All-In Emana Preta Invisível",
    categorias: "Meias",
    caption2: "Meia All-in Emana Preta Invisível - Conforto, Tecnologia e Performance | All-in    A Meia ...",
    price: "R$ 99,90",
    promotion: "",
    parcelasValor: "5x de  R$ 19,98",
    produtoTag: ""
  },
  {
    id: "355",
    linkProduto: "https://allinbrasil.com.br/loja/index.php?route=product/product&product_id=355",
    imgSrc: "https://s3-sa-east-1.amazonaws.com/public-http-cache/UploadArquivo/Arquivos/all_in_esp_br/loja/image/cache/catalog-3610-meias-brancas-alta-800x945.png",
    imgSrc2: "",
    caption: "Meia Cano Longo Branca",
    categorias: "Meias",
    caption2: "Meia All-in Emana Branca Cano LONGO - Conforto, Tecnologia e Bem-Estar | All-inA Meia All-in Emana ...",
    price: "R$ 129,00",
    promotion: "",
    parcelasValor: "5x de  R$ 25,80",
    produtoTag: ""
  },
  {
    id: "356",
    linkProduto: "https://allinbrasil.com.br/loja/index.php?route=product/product&product_id=356",
    imgSrc: "https://s3-sa-east-1.amazonaws.com/public-http-cache/UploadArquivo/Arquivos/all_in_esp_br/loja/image/cache/catalog-2216-meias-preta-800x945.png",
    imgSrc2: "",
    caption: "Meia Cano Longo Preta",
    categorias: "Meias",
    caption2: "Meia All-in Emana Preta Cano LONGO - Tecnologia Emana para Bem-Estar e Conforto | All-inA Meia ...",
    price: "R$ 129,00",
    promotion: "",
    parcelasValor: "5x de  R$ 25,80",
    produtoTag: ""
  },
  {
    id: "333",
    linkProduto: "https://allinbrasil.com.br/loja/index.php?route=product/product&product_id=333",
    imgSrc: "https://s3-sa-east-1.amazonaws.com/public-http-cache/UploadArquivo/Arquivos/all_in_esp_br/loja/image/cache/catalog-5724-calca-skinny-emana-2-800x945.png",
    imgSrc2: "https://s3-sa-east-1.amazonaws.com/public-http-cache/UploadArquivo/Arquivos/all_in_esp_br/loja/image/cache/catalog-4418-calca-skinny-emana-1-800x945.png",
    caption: "Calça Skinny Emana G",
    categorias: "Roupas",
    caption2: "Calça Skinny Emana G - Tecnologia Avançada para o Seu Corpo    A All-in traz para você a in...",
    price: "R$ 459,00",
    promotion: "",
    parcelasValor: "5x de  R$ 91,80",
    produtoTag: ""
  },
  {
    id: "334",
    linkProduto: "https://allinbrasil.com.br/loja/index.php?route=product/product&product_id=334",
    imgSrc: "https://s3-sa-east-1.amazonaws.com/public-http-cache/UploadArquivo/Arquivos/all_in_esp_br/loja/image/cache/catalog-3951-calca-800x945.jpg",
    imgSrc2: "",
    caption: "Calça Skinny Emana Gg",
    categorias: "Roupas",
    caption2: "Calça Skinny Emana GG - Tecnologia e Conforto para o Seu Corpo    A All-in desenvolveu uma ...",
    price: "R$ 459,00",
    promotion: "",
    parcelasValor: "5x de  R$ 91,80",
    produtoTag: ""
  },
  {
    id: "332",
    linkProduto: "https://allinbrasil.com.br/loja/index.php?route=product/product&product_id=332",
    imgSrc: "https://s3-sa-east-1.amazonaws.com/public-http-cache/UploadArquivo/Arquivos/all_in_esp_br/loja/image/cache/catalog-4579-calca-skinny-emana-3-800x945.png",
    imgSrc2: "https://s3-sa-east-1.amazonaws.com/public-http-cache/UploadArquivo/Arquivos/all_in_esp_br/loja/image/cache/catalog-4418-calca-skinny-emana-1-800x945.png",
    caption: "Calça Skinny Emana M",
    categorias: "Roupas",
    caption2: "Calça Skinny Emana M - Tecnologia e Conforto para o Seu Corpo    A All-in desenvolveu uma linha ...",
    price: "R$ 459,00",
    promotion: "",
    parcelasValor: "5x de  R$ 91,80",
    produtoTag: ""
  },
  {
    id: "331",
    linkProduto: "https://allinbrasil.com.br/loja/index.php?route=product/product&product_id=331",
    imgSrc: "https://s3-sa-east-1.amazonaws.com/public-http-cache/UploadArquivo/Arquivos/all_in_esp_br/loja/image/cache/catalog-4418-calca-skinny-emana-1-800x945.png",
    imgSrc2: "https://s3-sa-east-1.amazonaws.com/public-http-cache/UploadArquivo/Arquivos/all_in_esp_br/loja/image/cache/catalog-4579-calca-skinny-emana-3-800x945.png",
    caption: "Calça Skinny Emana P",
    categorias: "Roupas",
    caption2: "Calça Skinny Emana P - Tecnologia e Conforto para o Seu Corpo    A All-in desenvolveu uma linha ...",
    price: "R$ 459,00",
    promotion: "",
    parcelasValor: "5x de  R$ 91,80",
    produtoTag: ""
  },
  {
    id: "6",
    linkProduto: "https://allinbrasil.com.br/loja/index.php?route=product/product&product_id=6",
    imgSrc: "https://s3-sa-east-1.amazonaws.com/public-http-cache/UploadArquivo/Arquivos/all_in_esp_br/loja/image/cache/catalog-8419-branco1cortt-800x945.jpg",
    imgSrc2: "https://s3-sa-east-1.amazonaws.com/public-http-cache/UploadArquivo/Arquivos/all_in_esp_br/loja/image/cache/catalog-4255-branco3cort-800x945.jpg",
    caption: "Tênis All Classic Branco Off White",
    categorias: "Tênis",
    caption2: "ALL CLASSIC BRANCO OFF WHITE",
    price: "R$ 489,00",
    promotion: "",
    parcelasValor: "5x de  R$ 97,80",
    produtoTag: ""
  },
  {
    id: "77",
    linkProduto: "https://allinbrasil.com.br/loja/TENIS%20ESSENCE%20PRETA%20TERAPEUTICO",
    imgSrc: "https://s3-sa-east-1.amazonaws.com/public-http-cache/UploadArquivo/Arquivos/all_in_esp_br/loja/image/cache/catalog-1911-essence-01-1-800x945.jpg",
    imgSrc2: "https://s3-sa-east-1.amazonaws.com/public-http-cache/UploadArquivo/Arquivos/all_in_esp_br/loja/image/cache/catalog-1815-essence-01-2-800x945.jpg",
    caption: "Tênis All Essence Preto",
    categorias: "Tênis",
    caption2: "All In Essence – A Essência do Conforto e Estilo\nO All In Essence representa a fusão perfeita ent...",
    price: "R$ 499,00",
    promotion: "",
    parcelasValor: "5x de  R$ 99,80",
    produtoTag: ""
  },
  {
    id: "77",
    linkProduto: "https://allinbrasil.com.br/loja/index.php?route=product/product&product_id=77",
    imgSrc: "https://s3-sa-east-1.amazonaws.com/public-http-cache/UploadArquivo/Arquivos/all_in_esp_br/loja/image/cache/catalog-6137-shine-preto-800x945.jpg",
    imgSrc2: "",
    caption: "Tênis All Shine Preto",
    categorias: "Tênis",
    caption2: "Tênis All Shine Preto - Conforto, Estilo e Terapia para o Dia a Dia    O Tênis All Shine Preto é...",
    price: "R$ 489,00",
    promotion: "R$ 399,00",
    parcelasValor: "5x de  R$ 79,80",
    produtoTag: "Limitado"
  },
  {
    id: "74",
    linkProduto: "https://allinbrasil.com.br/loja/index.php?route=product/product&product_id=74",
    imgSrc: "https://s3-sa-east-1.amazonaws.com/public-http-cache/UploadArquivo/Arquivos/all_in_esp_br/loja/image/cache/catalog-8261-total-black-800x945.png",
    imgSrc2: "",
    caption: "Tênis All Sport Total Black",
    categorias: "Tênis",
    caption2: "Tênis All Sport Total Black - Conforto, Estilo e Benefícios Tecnológicos para o Uso Diário    O Tên...",
    price: "R$ 489,00",
    promotion: "",
    parcelasValor: "5x de  R$ 97,80",
    produtoTag: "Limitado"
  },
  {
    id: "348",
    linkProduto: "https://allinbrasil.com.br/loja/index.php?route=product/product&product_id=348",
    imgSrc: "https://s3-sa-east-1.amazonaws.com/public-http-cache/UploadArquivo/Arquivos/all_in_esp_br/loja/image/cache/catalog-6977-nude-reto-800x945.png",
    imgSrc2: "https://s3-sa-east-1.amazonaws.com/public-http-cache/UploadArquivo/Arquivos/all_in_esp_br/loja/image/cache/catalog-8919-basic-novo-800x945.png",
    caption: "Tênis Basic Nude",
    categorias: "Tênis",
    caption2: "BASIC NUDE",
    price: "R$ 399,00",
    promotion: "",
    parcelasValor: "5x de  R$ 79,80",
    produtoTag: "Limitado"
  },
  {
    id: "349",
    linkProduto: "https://allinbrasil.com.br/loja/index.php?route=product/product&product_id=349",
    imgSrc: "https://s3-sa-east-1.amazonaws.com/public-http-cache/UploadArquivo/Arquivos/all_in_esp_br/loja/image/cache/catalog-3966-basic-preto01-800x945.png",
    imgSrc2: "https://s3-sa-east-1.amazonaws.com/public-http-cache/UploadArquivo/Arquivos/all_in_esp_br/loja/image/cache/catalog-1726-basic-preto02-800x945.png",
    caption: "Tênis Basic Preto",
    categorias: "Tênis",
    caption2: "BASIC PRETO",
    price: "R$ 399,00",
    promotion: "",
    parcelasValor: "5x de  R$ 79,80",
    produtoTag: "Limitado"
  },
  {
    id: "23",
    linkProduto: "https://allinbrasil.com.br/loja/index.php?route=product/product&product_id=23",
    imgSrc: "https://s3-sa-east-1.amazonaws.com/public-http-cache/UploadArquivo/Arquivos/all_in_esp_br/loja/image/cache/catalog-3145-bumper-black-2-800x945.png",
    imgSrc2: "https://s3-sa-east-1.amazonaws.com/public-http-cache/UploadArquivo/Arquivos/all_in_esp_br/loja/image/cache/catalog-1754-bumper-black-1-800x945.png",
    caption: "Tênis Bumper Black",
    categorias: "Tênis",
    caption2: "Tênis Bumper Black – Moderno, Versátil e Cheio de Atitude\nO Tênis Bumper Black foi desenvolvido para...",
    price: "R$ 499,00",
    promotion: "",
    parcelasValor: "5x de  R$ 99,80",
    produtoTag: ""
  },
  {
    id: "23",
    linkProduto: "https://allinbrasil.com.br/loja/alta-tecnologia-em-terapias",
    imgSrc: "https://s3-sa-east-1.amazonaws.com/public-http-cache/UploadArquivo/Arquivos/all_in_esp_br/loja/image/cache/catalog-4569-bumper-white-1-800x945.png",
    imgSrc2: "https://s3-sa-east-1.amazonaws.com/public-http-cache/UploadArquivo/Arquivos/all_in_esp_br/loja/image/cache/catalog-8312-bumper-white-3-800x945.png",
    caption: "Tênis Bumper White",
    categorias: "Tênis",
    caption2: "Tênis Bumper Branco Feminino – Estilo e Conforto em Cada Passo\nO Tênis Bumper Branco Feminino é a esco...",
    price: "R$ 499,00",
    promotion: "",
    parcelasValor: "5x de  R$ 99,80",
    produtoTag: ""
  },
  {
    id: "19",
    linkProduto: "https://allinbrasil.com.br/loja/index.php?route=product/product&product_id=19",
    imgSrc: "https://s3-sa-east-1.amazonaws.com/public-http-cache/UploadArquivo/Arquivos/all_in_esp_br/loja/image/cache/catalog-2792-casual-black-1-800x945.png",
    imgSrc2: "https://s3-sa-east-1.amazonaws.com/public-http-cache/UploadArquivo/Arquivos/all_in_esp_br/loja/image/cache/catalog-7443-casual-black-3-800x945.png",
    caption: "Tênis Casuall Black",
    categorias: "Tênis",
    caption2: "Tênis Casuall Black - Conforto Tecnológico e Estilo para o Dia a Dia    O Tênis Casuall Black of...",
    price: "R$ 469,00",
    promotion: "",
    parcelasValor: "5x de  R$ 93,80",
    produtoTag: "Limitado"
  },
  {
    id: "20",
    linkProduto: "https://allinbrasil.com.br/loja/index.php?route=product/product&product_id=20",
    imgSrc: "https://s3-sa-east-1.amazonaws.com/public-http-cache/UploadArquivo/Arquivos/all_in_esp_br/loja/image/cache/catalog-3460-casual-green-800x945.jpeg",
    imgSrc2: "",
    caption: "Tênis Casuall Green",
    categorias: "Tênis",
    caption2: "Tênis Casuall Green - Conforto Tecnológico e Estilo para o Dia a Dia    O Tênis Casuall Green of...",
    price: "R$ 469,00",
    promotion: "",
    parcelasValor: "5x de  R$ 93,80",
    produtoTag: "-35%"
  },
  {
    id: "300",
    linkProduto: "https://allinbrasil.com.br/loja/index.php?route=product/product&product_id=300",
    imgSrc: "https://s3-sa-east-1.amazonaws.com/public-http-cache/UploadArquivo/Arquivos/all_in_esp_br/loja/image/cache/catalog-9976-casual-grey-2-800x945.png",
    imgSrc2: "https://s3-sa-east-1.amazonaws.com/public-http-cache/UploadArquivo/Arquivos/all_in_esp_br/loja/image/cache/catalog-8211-casual-grey-1-800x945.png",
    caption: "Tênis Casuall Grey",
    categorias: "Tênis",
    caption2: "Tênis Casuall Grey - Conforto e Terapia para o Seu Dia a Dia    O Tênis Casuall Grey é a es...",
    price: "R$ 469,00",
    promotion: "",
    parcelasValor: "5x de  R$ 93,80",
    produtoTag: "Limitado"
  },
  {
    id: "354",
    linkProduto: "https://allinbrasil.com.br/loja/index.php?route=product/product&product_id=354",
    imgSrc: "https://s3-sa-east-1.amazonaws.com/public-http-cache/UploadArquivo/Arquivos/all_in_esp_br/loja/image/cache/catalog-4999-caaa-800x945.jpeg",
    imgSrc2: "https://s3-sa-east-1.amazonaws.com/public-http-cache/UploadArquivo/Arquivos/all_in_esp_br/loja/image/cache/catalog-3107-casuuu-800x945.jpg",
    caption: "Tênis Casuall Ultra Black",
    categorias: "Tênis",
    caption2: "Tênis\nCasual Ultra Black \nO Tênis Casual Ultra Black\nredefine o conceito de calçado casual mas...",
    price: "R$ 489,00",
    promotion: "",
    parcelasValor: "5x de  R$ 97,80",
    produtoTag: "LANÇAMENTO"
  },
  {
    id: "13",
    linkProduto: "https://allinbrasil.com.br/loja/index.php?route=product/product&product_id=13",
    imgSrc: "https://s3-sa-east-1.amazonaws.com/public-http-cache/UploadArquivo/Arquivos/all_in_esp_br/loja/image/cache/catalog-7754-classic-all-black-1-800x945.png",
    imgSrc2: "https://s3-sa-east-1.amazonaws.com/public-http-cache/UploadArquivo/Arquivos/all_in_esp_br/loja/image/cache/catalog-2220-classic-all-black-3-800x945.png",
    caption: "Tênis Classic All Black",
    categorias: "Tênis",
    caption2: "Tênis Classic All Black - Estilo, Conforto e Terapia no Seu Dia a Dia    O Tênis Classic All B...",
    price: "R$ 489,00",
    promotion: "",
    parcelasValor: "5x de  R$ 97,80",
    produtoTag: ""
  },
  {
    id: "8",
    linkProduto: "https://allinbrasil.com.br/loja/index.php?route=product/product&product_id=8",
    imgSrc: "https://s3-sa-east-1.amazonaws.com/public-http-cache/UploadArquivo/Arquivos/all_in_esp_br/loja/image/cache/catalog-2953-classic-azul-2-800x945.png",
    imgSrc2: "https://s3-sa-east-1.amazonaws.com/public-http-cache/UploadArquivo/Arquivos/all_in_esp_br/loja/image/cache/catalog-3748-classic-azul-1-800x945.png",
    caption: "Tênis Classic Azul",
    categorias: "Tênis",
    caption2: "Tênis Classic Azul - Estilo, Conforto e Terapia no Seu             Dia a Dia             ...",
    price: "R$ 469,00",
    promotion: "",
    parcelasValor: "5x de  R$ 93,80",
    produtoTag: "Limitado"
  },
  {
    id: "38",
    linkProduto: "https://allinbrasil.com.br/loja/t%C3%AAnis%20cinza%20terap%C3%AAuticos",
    imgSrc: "https://s3-sa-east-1.amazonaws.com/public-http-cache/UploadArquivo/Arquivos/all_in_esp_br/loja/image/cache/catalog-2532-classic-chumbo-1-800x945.png",
    imgSrc2: "https://s3-sa-east-1.amazonaws.com/public-http-cache/UploadArquivo/Arquivos/all_in_esp_br/loja/image/cache/catalog-2043-classic-chumbo-3-800x945.png",
    caption: "Tênis Classic Chumbo",
    categorias: "Tênis",
    caption2: "Tênis Classic Chumbo - Estilo, Conforto e Terapia no Seu Dia a Dia    O Tênis Classic Chumbo c...",
    price: "R$ 489,00",
    promotion: "",
    parcelasValor: "5x de  R$ 97,80",
    produtoTag: "Limitado"
  },
  {
    id: "38",
    linkProduto: "https://allinbrasil.com.br/loja/index.php?route=product/product&product_id=38",
    imgSrc: "https://s3-sa-east-1.amazonaws.com/public-http-cache/UploadArquivo/Arquivos/all_in_esp_br/loja/image/cache/catalog-5118-classic-linho-1-800x945.png",
    imgSrc2: "https://s3-sa-east-1.amazonaws.com/public-http-cache/UploadArquivo/Arquivos/all_in_esp_br/loja/image/cache/catalog-9583-classic-linho-3-800x945.png",
    caption: "Tênis Classic Linho Reciclado",
    categorias: "Tênis",
    caption2: "Tênis Classic Linho Reciclado - Estilo Sustentável, Conforto e Bem-Estar    O Tênis Classic Li...",
    price: "R$ 489,00",
    promotion: "",
    parcelasValor: "5x de  R$ 97,80",
    produtoTag: ""
  },
  {
    id: "353",
    linkProduto: "https://allinbrasil.com.br/loja/index.php?route=product/product&product_id=353",
    imgSrc: "https://s3-sa-east-1.amazonaws.com/public-http-cache/UploadArquivo/Arquivos/all_in_esp_br/loja/image/cache/catalog-7628-mocha2-800x945.jpg",
    imgSrc2: "",
    caption: "Tênis Classic Mocha Mousse",
    categorias: "Tênis",
    caption2: "Tênis Classic Mocha Mousse - Estilo, Conforto e Terapia no Seu Dia a DiaO Tênis Classic Mocha Mo...",
    price: "R$ 489,00",
    promotion: "",
    parcelasValor: "5x de  R$ 97,80",
    produtoTag: "Limitado"
  },
  {
    id: "353",
    linkProduto: "https://allinbrasil.com.br/loja/t%C3%AAnis%20preto%20terap%C3%AAuticos",
    imgSrc: "https://s3-sa-east-1.amazonaws.com/public-http-cache/UploadArquivo/Arquivos/all_in_esp_br/loja/image/cache/catalog-6120-classic-preto-1-800x945.png",
    imgSrc2: "https://s3-sa-east-1.amazonaws.com/public-http-cache/UploadArquivo/Arquivos/all_in_esp_br/loja/image/cache/catalog-8160-classic-preto-3-800x945.png",
    caption: "Tênis Classic Preto",
    categorias: "Tênis",
    caption2: "Tênis Classic Preto - Estilo, Conforto e Terapia para Seus Pés    O Tênis Classic Preto traz o eq...",
    price: "R$ 489,00",
    promotion: "",
    parcelasValor: "5x de  R$ 97,80",
    produtoTag: ""
  },
  {
    id: "350",
    linkProduto: "https://allinbrasil.com.br/loja/index.php?route=product/product&product_id=350",
    imgSrc: "https://s3-sa-east-1.amazonaws.com/public-http-cache/UploadArquivo/Arquivos/all_in_esp_br/loja/image/cache/catalog-1176-balance-novo-black-800x945.png",
    imgSrc2: "https://s3-sa-east-1.amazonaws.com/public-http-cache/UploadArquivo/Arquivos/all_in_esp_br/loja/image/cache/catalog-4344-balance-black-2-800x945.png",
    caption: "Tênis Sport Balance Black",
    categorias: "Tênis",
    caption2: "SPORT BALANCE BLACK",
    price: "R$ 519,00",
    promotion: "",
    parcelasValor: "5x de  R$ 103,80",
    produtoTag: "Limitado"
  },
  {
    id: "351",
    linkProduto: "https://allinbrasil.com.br/loja/index.php?route=product/product&product_id=351",
    imgSrc: "https://s3-sa-east-1.amazonaws.com/public-http-cache/UploadArquivo/Arquivos/all_in_esp_br/loja/image/cache/catalog-2173-balance-laranja-2-800x945.png",
    imgSrc2: "https://s3-sa-east-1.amazonaws.com/public-http-cache/UploadArquivo/Arquivos/all_in_esp_br/loja/image/cache/catalog-7002-balance-laranja-1-800x945.png",
    caption: "Tênis Sport Balance Laranja",
    categorias: "Tênis",
    caption2: "SPORT BALANCE LARANJA",
    price: "R$ 519,00",
    promotion: "",
    parcelasValor: "5x de  R$ 103,80",
    produtoTag: "Limitado"
  },
  {
    id: "336",
    linkProduto: "https://allinbrasil.com.br/loja/index.php?route=product/product&product_id=336",
    imgSrc: "https://s3-sa-east-1.amazonaws.com/public-http-cache/UploadArquivo/Arquivos/all_in_esp_br/loja/image/cache/catalog-1404-sport-balance-nude-1-800x945.png",
    imgSrc2: "https://s3-sa-east-1.amazonaws.com/public-http-cache/UploadArquivo/Arquivos/all_in_esp_br/loja/image/cache/catalog-6033-sport-balance-nude-2-800x945.png",
    caption: "Tênis Sport Balance Nude",
    categorias: "Tênis",
    caption2: "SPORT BALANCE NUDE",
    price: "R$ 519,00",
    promotion: "",
    parcelasValor: "5x de  R$ 103,80",
    produtoTag: ""
  },
  {
    id: "335",
    linkProduto: "https://allinbrasil.com.br/loja/index.php?route=product/product&product_id=335",
    imgSrc: "https://s3-sa-east-1.amazonaws.com/public-http-cache/UploadArquivo/Arquivos/all_in_esp_br/loja/image/cache/catalog-8432-sport-balance-preto-1-800x945.png",
    imgSrc2: "https://s3-sa-east-1.amazonaws.com/public-http-cache/UploadArquivo/Arquivos/all_in_esp_br/loja/image/cache/catalog-3232-sport-balance-preto-2-800x945.png",
    caption: "Tênis Sport Balance Preto",
    categorias: "Tênis",
    caption2: "SPORT BALANCE PRETO",
    price: "R$ 519,00",
    promotion: "",
    parcelasValor: "5x de  R$ 103,80",
    produtoTag: ""
  }
];
