/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OfficeRouteImport } from './routes/office'
import { Route as AppRouteImport } from './routes/_app'
import { Route as OfficeIndexRouteImport } from './routes/office/index'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as OfficeStoreRouteImport } from './routes/office/store'
import { Route as OfficePlanRouteImport } from './routes/office/plan'
import { Route as OfficeOrdersRouteImport } from './routes/office/orders'
import { Route as OfficeFinanceRouteImport } from './routes/office/finance'
import { Route as AppWalletsRouteImport } from './routes/_app/wallets'
import { Route as AppSystemRouteImport } from './routes/_app/system'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppPlansRouteImport } from './routes/_app/plans'
import { Route as AppNetworkRouteImport } from './routes/_app/network'
import { Route as AppMarketingRouteImport } from './routes/_app/marketing'
import { Route as AppInsightsRouteImport } from './routes/_app/insights'
import { Route as AppCopilotRouteImport } from './routes/_app/copilot'
import { Route as AppCommissionsRouteImport } from './routes/_app/commissions'
import { Route as AppAnalyticsRouteImport } from './routes/_app/analytics'
import { Route as AppAlertsRouteImport } from './routes/_app/alerts'
import { Route as AppProductsIndexRouteImport } from './routes/_app/products/index'
import { Route as AppOrdersIndexRouteImport } from './routes/_app/orders/index'
import { Route as AppCustomersIndexRouteImport } from './routes/_app/customers/index'
import { Route as AppCustomersIdRouteImport } from './routes/_app/customers/$id'

const OfficeRoute = OfficeRouteImport.update({
  id: '/office',
  path: '/office',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeIndexRoute = OfficeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OfficeRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const OfficeStoreRoute = OfficeStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => OfficeRoute,
} as any)
const OfficePlanRoute = OfficePlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => OfficeRoute,
} as any)
const OfficeOrdersRoute = OfficeOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => OfficeRoute,
} as any)
const OfficeFinanceRoute = OfficeFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => OfficeRoute,
} as any)
const AppWalletsRoute = AppWalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => AppRoute,
} as any)
const AppSystemRoute = AppSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPlansRoute = AppPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AppRoute,
} as any)
const AppNetworkRoute = AppNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketingRoute = AppMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightsRoute = AppInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppRoute,
} as any)
const AppCopilotRoute = AppCopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => AppRoute,
} as any)
const AppCommissionsRoute = AppCommissionsRouteImport.update({
  id: '/commissions',
  path: '/commissions',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsIndexRoute = AppProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersIndexRoute = AppOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersIndexRoute = AppCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersIdRoute = AppCustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/office': typeof OfficeRouteWithChildren
  '/alerts': typeof AppAlertsRoute
  '/analytics': typeof AppAnalyticsRoute
  '/commissions': typeof AppCommissionsRoute
  '/copilot': typeof AppCopilotRoute
  '/insights': typeof AppInsightsRoute
  '/marketing': typeof AppMarketingRoute
  '/network': typeof AppNetworkRoute
  '/plans': typeof AppPlansRoute
  '/settings': typeof AppSettingsRoute
  '/system': typeof AppSystemRoute
  '/wallets': typeof AppWalletsRoute
  '/office/finance': typeof OfficeFinanceRoute
  '/office/orders': typeof OfficeOrdersRoute
  '/office/plan': typeof OfficePlanRoute
  '/office/store': typeof OfficeStoreRoute
  '/office/': typeof OfficeIndexRoute
  '/customers/$id': typeof AppCustomersIdRoute
  '/customers/': typeof AppCustomersIndexRoute
  '/orders/': typeof AppOrdersIndexRoute
  '/products/': typeof AppProductsIndexRoute
}
export interface FileRoutesByTo {
  '/alerts': typeof AppAlertsRoute
  '/analytics': typeof AppAnalyticsRoute
  '/commissions': typeof AppCommissionsRoute
  '/copilot': typeof AppCopilotRoute
  '/insights': typeof AppInsightsRoute
  '/marketing': typeof AppMarketingRoute
  '/network': typeof AppNetworkRoute
  '/plans': typeof AppPlansRoute
  '/settings': typeof AppSettingsRoute
  '/system': typeof AppSystemRoute
  '/wallets': typeof AppWalletsRoute
  '/office/finance': typeof OfficeFinanceRoute
  '/office/orders': typeof OfficeOrdersRoute
  '/office/plan': typeof OfficePlanRoute
  '/office/store': typeof OfficeStoreRoute
  '/': typeof AppIndexRoute
  '/office': typeof OfficeIndexRoute
  '/customers/$id': typeof AppCustomersIdRoute
  '/customers': typeof AppCustomersIndexRoute
  '/orders': typeof AppOrdersIndexRoute
  '/products': typeof AppProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/office': typeof OfficeRouteWithChildren
  '/_app/alerts': typeof AppAlertsRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/commissions': typeof AppCommissionsRoute
  '/_app/copilot': typeof AppCopilotRoute
  '/_app/insights': typeof AppInsightsRoute
  '/_app/marketing': typeof AppMarketingRoute
  '/_app/network': typeof AppNetworkRoute
  '/_app/plans': typeof AppPlansRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/system': typeof AppSystemRoute
  '/_app/wallets': typeof AppWalletsRoute
  '/office/finance': typeof OfficeFinanceRoute
  '/office/orders': typeof OfficeOrdersRoute
  '/office/plan': typeof OfficePlanRoute
  '/office/store': typeof OfficeStoreRoute
  '/_app/': typeof AppIndexRoute
  '/office/': typeof OfficeIndexRoute
  '/_app/customers/$id': typeof AppCustomersIdRoute
  '/_app/customers/': typeof AppCustomersIndexRoute
  '/_app/orders/': typeof AppOrdersIndexRoute
  '/_app/products/': typeof AppProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/office'
    | '/alerts'
    | '/analytics'
    | '/commissions'
    | '/copilot'
    | '/insights'
    | '/marketing'
    | '/network'
    | '/plans'
    | '/settings'
    | '/system'
    | '/wallets'
    | '/office/finance'
    | '/office/orders'
    | '/office/plan'
    | '/office/store'
    | '/office/'
    | '/customers/$id'
    | '/customers/'
    | '/orders/'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/alerts'
    | '/analytics'
    | '/commissions'
    | '/copilot'
    | '/insights'
    | '/marketing'
    | '/network'
    | '/plans'
    | '/settings'
    | '/system'
    | '/wallets'
    | '/office/finance'
    | '/office/orders'
    | '/office/plan'
    | '/office/store'
    | '/'
    | '/office'
    | '/customers/$id'
    | '/customers'
    | '/orders'
    | '/products'
  id:
    | '__root__'
    | '/_app'
    | '/office'
    | '/_app/alerts'
    | '/_app/analytics'
    | '/_app/commissions'
    | '/_app/copilot'
    | '/_app/insights'
    | '/_app/marketing'
    | '/_app/network'
    | '/_app/plans'
    | '/_app/settings'
    | '/_app/system'
    | '/_app/wallets'
    | '/office/finance'
    | '/office/orders'
    | '/office/plan'
    | '/office/store'
    | '/_app/'
    | '/office/'
    | '/_app/customers/$id'
    | '/_app/customers/'
    | '/_app/orders/'
    | '/_app/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  OfficeRoute: typeof OfficeRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/office': {
      id: '/office'
      path: '/office'
      fullPath: '/office'
      preLoaderRoute: typeof OfficeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office/': {
      id: '/office/'
      path: '/'
      fullPath: '/office/'
      preLoaderRoute: typeof OfficeIndexRouteImport
      parentRoute: typeof OfficeRoute
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/office/store': {
      id: '/office/store'
      path: '/store'
      fullPath: '/office/store'
      preLoaderRoute: typeof OfficeStoreRouteImport
      parentRoute: typeof OfficeRoute
    }
    '/office/plan': {
      id: '/office/plan'
      path: '/plan'
      fullPath: '/office/plan'
      preLoaderRoute: typeof OfficePlanRouteImport
      parentRoute: typeof OfficeRoute
    }
    '/office/orders': {
      id: '/office/orders'
      path: '/orders'
      fullPath: '/office/orders'
      preLoaderRoute: typeof OfficeOrdersRouteImport
      parentRoute: typeof OfficeRoute
    }
    '/office/finance': {
      id: '/office/finance'
      path: '/finance'
      fullPath: '/office/finance'
      preLoaderRoute: typeof OfficeFinanceRouteImport
      parentRoute: typeof OfficeRoute
    }
    '/_app/wallets': {
      id: '/_app/wallets'
      path: '/wallets'
      fullPath: '/wallets'
      preLoaderRoute: typeof AppWalletsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/system': {
      id: '/_app/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof AppSystemRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plans': {
      id: '/_app/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof AppPlansRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/network': {
      id: '/_app/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof AppNetworkRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/marketing': {
      id: '/_app/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof AppMarketingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/insights': {
      id: '/_app/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AppInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/copilot': {
      id: '/_app/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof AppCopilotRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/commissions': {
      id: '/_app/commissions'
      path: '/commissions'
      fullPath: '/commissions'
      preLoaderRoute: typeof AppCommissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alerts': {
      id: '/_app/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products/': {
      id: '/_app/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AppProductsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders/': {
      id: '/_app/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof AppOrdersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers/': {
      id: '/_app/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AppCustomersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers/$id': {
      id: '/_app/customers/$id'
      path: '/customers/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof AppCustomersIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAlertsRoute: typeof AppAlertsRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppCommissionsRoute: typeof AppCommissionsRoute
  AppCopilotRoute: typeof AppCopilotRoute
  AppInsightsRoute: typeof AppInsightsRoute
  AppMarketingRoute: typeof AppMarketingRoute
  AppNetworkRoute: typeof AppNetworkRoute
  AppPlansRoute: typeof AppPlansRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSystemRoute: typeof AppSystemRoute
  AppWalletsRoute: typeof AppWalletsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCustomersIdRoute: typeof AppCustomersIdRoute
  AppCustomersIndexRoute: typeof AppCustomersIndexRoute
  AppOrdersIndexRoute: typeof AppOrdersIndexRoute
  AppProductsIndexRoute: typeof AppProductsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlertsRoute: AppAlertsRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppCommissionsRoute: AppCommissionsRoute,
  AppCopilotRoute: AppCopilotRoute,
  AppInsightsRoute: AppInsightsRoute,
  AppMarketingRoute: AppMarketingRoute,
  AppNetworkRoute: AppNetworkRoute,
  AppPlansRoute: AppPlansRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSystemRoute: AppSystemRoute,
  AppWalletsRoute: AppWalletsRoute,
  AppIndexRoute: AppIndexRoute,
  AppCustomersIdRoute: AppCustomersIdRoute,
  AppCustomersIndexRoute: AppCustomersIndexRoute,
  AppOrdersIndexRoute: AppOrdersIndexRoute,
  AppProductsIndexRoute: AppProductsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface OfficeRouteChildren {
  OfficeFinanceRoute: typeof OfficeFinanceRoute
  OfficeOrdersRoute: typeof OfficeOrdersRoute
  OfficePlanRoute: typeof OfficePlanRoute
  OfficeStoreRoute: typeof OfficeStoreRoute
  OfficeIndexRoute: typeof OfficeIndexRoute
}

const OfficeRouteChildren: OfficeRouteChildren = {
  OfficeFinanceRoute: OfficeFinanceRoute,
  OfficeOrdersRoute: OfficeOrdersRoute,
  OfficePlanRoute: OfficePlanRoute,
  OfficeStoreRoute: OfficeStoreRoute,
  OfficeIndexRoute: OfficeIndexRoute,
}

const OfficeRouteWithChildren =
  OfficeRoute._addFileChildren(OfficeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  OfficeRoute: OfficeRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
