/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SejaDistribuidorRouteImport } from './routes/seja-distribuidor'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as OfficeRouteImport } from './routes/office'
import { Route as LojaRouteImport } from './routes/loja'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DoencasRouteImport } from './routes/doencas'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as BuscaProdutosRouteImport } from './routes/busca-produtos'
import { Route as AtivacaoRouteImport } from './routes/ativacao'
import { Route as AppRouteImport } from './routes/_app'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OfficeIndexRouteImport } from './routes/office/index'
import { Route as SejaDistribuidorSlugRouteImport } from './routes/seja-distribuidor.$slug'
import { Route as ProdutoIdRouteImport } from './routes/produto.$id'
import { Route as OfficeVerificationRouteImport } from './routes/office/verification'
import { Route as OfficeStoreRouteImport } from './routes/office/store'
import { Route as OfficeReportsRouteImport } from './routes/office/reports'
import { Route as OfficeProfileRouteImport } from './routes/office/profile'
import { Route as OfficePlanRouteImport } from './routes/office/plan'
import { Route as OfficeOrdersRouteImport } from './routes/office/orders'
import { Route as OfficeNetworkRouteImport } from './routes/office/network'
import { Route as OfficeFinanceRouteImport } from './routes/office/finance'
import { Route as OfficeDownloadsRouteImport } from './routes/office/downloads'
import { Route as OfficeCopilotRouteImport } from './routes/office/copilot'
import { Route as LojaSlugRouteImport } from './routes/loja.$slug'
import { Route as DoencasSlugRouteImport } from './routes/doencas.$slug'
import { Route as BuscaProdutosSlugRouteImport } from './routes/busca-produtos.$slug'
import { Route as AppWalletsRouteImport } from './routes/_app/wallets'
import { Route as AppSystemRouteImport } from './routes/_app/system'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppPlansRouteImport } from './routes/_app/plans'
import { Route as AppNetworkRouteImport } from './routes/_app/network'
import { Route as AppMarketingRouteImport } from './routes/_app/marketing'
import { Route as AppInsightsRouteImport } from './routes/_app/insights'
import { Route as AppCopilotRouteImport } from './routes/_app/copilot'
import { Route as AppCommissionsRouteImport } from './routes/_app/commissions'
import { Route as AppAnalyticsRouteImport } from './routes/_app/analytics'
import { Route as AppAlertsRouteImport } from './routes/_app/alerts'
import { Route as AppProductsIndexRouteImport } from './routes/_app/products/index'
import { Route as AppOrdersIndexRouteImport } from './routes/_app/orders/index'
import { Route as AppCustomersIndexRouteImport } from './routes/_app/customers/index'
import { Route as AuthInviteTokenRouteImport } from './routes/auth.invite.$token'
import { Route as AppCustomersIdRouteImport } from './routes/_app/customers/$id'

const SejaDistribuidorRoute = SejaDistribuidorRouteImport.update({
  id: '/seja-distribuidor',
  path: '/seja-distribuidor',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeRoute = OfficeRouteImport.update({
  id: '/office',
  path: '/office',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaRoute = LojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DoencasRoute = DoencasRouteImport.update({
  id: '/doencas',
  path: '/doencas',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscaProdutosRoute = BuscaProdutosRouteImport.update({
  id: '/busca-produtos',
  path: '/busca-produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const AtivacaoRoute = AtivacaoRouteImport.update({
  id: '/ativacao',
  path: '/ativacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeIndexRoute = OfficeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OfficeRoute,
} as any)
const SejaDistribuidorSlugRoute = SejaDistribuidorSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SejaDistribuidorRoute,
} as any)
const ProdutoIdRoute = ProdutoIdRouteImport.update({
  id: '/produto/$id',
  path: '/produto/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeVerificationRoute = OfficeVerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => OfficeRoute,
} as any)
const OfficeStoreRoute = OfficeStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => OfficeRoute,
} as any)
const OfficeReportsRoute = OfficeReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => OfficeRoute,
} as any)
const OfficeProfileRoute = OfficeProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => OfficeRoute,
} as any)
const OfficePlanRoute = OfficePlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => OfficeRoute,
} as any)
const OfficeOrdersRoute = OfficeOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => OfficeRoute,
} as any)
const OfficeNetworkRoute = OfficeNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => OfficeRoute,
} as any)
const OfficeFinanceRoute = OfficeFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => OfficeRoute,
} as any)
const OfficeDownloadsRoute = OfficeDownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => OfficeRoute,
} as any)
const OfficeCopilotRoute = OfficeCopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => OfficeRoute,
} as any)
const LojaSlugRoute = LojaSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LojaRoute,
} as any)
const DoencasSlugRoute = DoencasSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DoencasRoute,
} as any)
const BuscaProdutosSlugRoute = BuscaProdutosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BuscaProdutosRoute,
} as any)
const AppWalletsRoute = AppWalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => AppRoute,
} as any)
const AppSystemRoute = AppSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPlansRoute = AppPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AppRoute,
} as any)
const AppNetworkRoute = AppNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketingRoute = AppMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightsRoute = AppInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppRoute,
} as any)
const AppCopilotRoute = AppCopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => AppRoute,
} as any)
const AppCommissionsRoute = AppCommissionsRouteImport.update({
  id: '/commissions',
  path: '/commissions',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsIndexRoute = AppProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersIndexRoute = AppOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersIndexRoute = AppCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AppRoute,
} as any)
const AuthInviteTokenRoute = AuthInviteTokenRouteImport.update({
  id: '/auth/invite/$token',
  path: '/auth/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCustomersIdRoute = AppCustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/ativacao': typeof AtivacaoRoute
  '/busca-produtos': typeof BuscaProdutosRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/checkout': typeof CheckoutRoute
  '/doencas': typeof DoencasRouteWithChildren
  '/login': typeof LoginRoute
  '/loja': typeof LojaRouteWithChildren
  '/office': typeof OfficeRouteWithChildren
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/seja-distribuidor': typeof SejaDistribuidorRouteWithChildren
  '/alerts': typeof AppAlertsRoute
  '/analytics': typeof AppAnalyticsRoute
  '/commissions': typeof AppCommissionsRoute
  '/copilot': typeof AppCopilotRoute
  '/insights': typeof AppInsightsRoute
  '/marketing': typeof AppMarketingRoute
  '/network': typeof AppNetworkRoute
  '/plans': typeof AppPlansRoute
  '/settings': typeof AppSettingsRoute
  '/system': typeof AppSystemRoute
  '/wallets': typeof AppWalletsRoute
  '/busca-produtos/$slug': typeof BuscaProdutosSlugRoute
  '/doencas/$slug': typeof DoencasSlugRoute
  '/loja/$slug': typeof LojaSlugRoute
  '/office/copilot': typeof OfficeCopilotRoute
  '/office/downloads': typeof OfficeDownloadsRoute
  '/office/finance': typeof OfficeFinanceRoute
  '/office/network': typeof OfficeNetworkRoute
  '/office/orders': typeof OfficeOrdersRoute
  '/office/plan': typeof OfficePlanRoute
  '/office/profile': typeof OfficeProfileRoute
  '/office/reports': typeof OfficeReportsRoute
  '/office/store': typeof OfficeStoreRoute
  '/office/verification': typeof OfficeVerificationRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/seja-distribuidor/$slug': typeof SejaDistribuidorSlugRoute
  '/office/': typeof OfficeIndexRoute
  '/customers/$id': typeof AppCustomersIdRoute
  '/auth/invite/$token': typeof AuthInviteTokenRoute
  '/customers/': typeof AppCustomersIndexRoute
  '/orders/': typeof AppOrdersIndexRoute
  '/products/': typeof AppProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/ativacao': typeof AtivacaoRoute
  '/busca-produtos': typeof BuscaProdutosRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/checkout': typeof CheckoutRoute
  '/doencas': typeof DoencasRouteWithChildren
  '/login': typeof LoginRoute
  '/loja': typeof LojaRouteWithChildren
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/seja-distribuidor': typeof SejaDistribuidorRouteWithChildren
  '/alerts': typeof AppAlertsRoute
  '/analytics': typeof AppAnalyticsRoute
  '/commissions': typeof AppCommissionsRoute
  '/copilot': typeof AppCopilotRoute
  '/insights': typeof AppInsightsRoute
  '/marketing': typeof AppMarketingRoute
  '/network': typeof AppNetworkRoute
  '/plans': typeof AppPlansRoute
  '/settings': typeof AppSettingsRoute
  '/system': typeof AppSystemRoute
  '/wallets': typeof AppWalletsRoute
  '/busca-produtos/$slug': typeof BuscaProdutosSlugRoute
  '/doencas/$slug': typeof DoencasSlugRoute
  '/loja/$slug': typeof LojaSlugRoute
  '/office/copilot': typeof OfficeCopilotRoute
  '/office/downloads': typeof OfficeDownloadsRoute
  '/office/finance': typeof OfficeFinanceRoute
  '/office/network': typeof OfficeNetworkRoute
  '/office/orders': typeof OfficeOrdersRoute
  '/office/plan': typeof OfficePlanRoute
  '/office/profile': typeof OfficeProfileRoute
  '/office/reports': typeof OfficeReportsRoute
  '/office/store': typeof OfficeStoreRoute
  '/office/verification': typeof OfficeVerificationRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/seja-distribuidor/$slug': typeof SejaDistribuidorSlugRoute
  '/office': typeof OfficeIndexRoute
  '/customers/$id': typeof AppCustomersIdRoute
  '/auth/invite/$token': typeof AuthInviteTokenRoute
  '/customers': typeof AppCustomersIndexRoute
  '/orders': typeof AppOrdersIndexRoute
  '/products': typeof AppProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/_app': typeof AppRouteWithChildren
  '/ativacao': typeof AtivacaoRoute
  '/busca-produtos': typeof BuscaProdutosRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/checkout': typeof CheckoutRoute
  '/doencas': typeof DoencasRouteWithChildren
  '/login': typeof LoginRoute
  '/loja': typeof LojaRouteWithChildren
  '/office': typeof OfficeRouteWithChildren
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/seja-distribuidor': typeof SejaDistribuidorRouteWithChildren
  '/_app/alerts': typeof AppAlertsRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/commissions': typeof AppCommissionsRoute
  '/_app/copilot': typeof AppCopilotRoute
  '/_app/insights': typeof AppInsightsRoute
  '/_app/marketing': typeof AppMarketingRoute
  '/_app/network': typeof AppNetworkRoute
  '/_app/plans': typeof AppPlansRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/system': typeof AppSystemRoute
  '/_app/wallets': typeof AppWalletsRoute
  '/busca-produtos/$slug': typeof BuscaProdutosSlugRoute
  '/doencas/$slug': typeof DoencasSlugRoute
  '/loja/$slug': typeof LojaSlugRoute
  '/office/copilot': typeof OfficeCopilotRoute
  '/office/downloads': typeof OfficeDownloadsRoute
  '/office/finance': typeof OfficeFinanceRoute
  '/office/network': typeof OfficeNetworkRoute
  '/office/orders': typeof OfficeOrdersRoute
  '/office/plan': typeof OfficePlanRoute
  '/office/profile': typeof OfficeProfileRoute
  '/office/reports': typeof OfficeReportsRoute
  '/office/store': typeof OfficeStoreRoute
  '/office/verification': typeof OfficeVerificationRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/seja-distribuidor/$slug': typeof SejaDistribuidorSlugRoute
  '/office/': typeof OfficeIndexRoute
  '/_app/customers/$id': typeof AppCustomersIdRoute
  '/auth/invite/$token': typeof AuthInviteTokenRoute
  '/_app/customers/': typeof AppCustomersIndexRoute
  '/_app/orders/': typeof AppOrdersIndexRoute
  '/_app/products/': typeof AppProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/ativacao'
    | '/busca-produtos'
    | '/cadastro'
    | '/checkout'
    | '/doencas'
    | '/login'
    | '/loja'
    | '/office'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/seja-distribuidor'
    | '/alerts'
    | '/analytics'
    | '/commissions'
    | '/copilot'
    | '/insights'
    | '/marketing'
    | '/network'
    | '/plans'
    | '/settings'
    | '/system'
    | '/wallets'
    | '/busca-produtos/$slug'
    | '/doencas/$slug'
    | '/loja/$slug'
    | '/office/copilot'
    | '/office/downloads'
    | '/office/finance'
    | '/office/network'
    | '/office/orders'
    | '/office/plan'
    | '/office/profile'
    | '/office/reports'
    | '/office/store'
    | '/office/verification'
    | '/produto/$id'
    | '/seja-distribuidor/$slug'
    | '/office/'
    | '/customers/$id'
    | '/auth/invite/$token'
    | '/customers/'
    | '/orders/'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/ativacao'
    | '/busca-produtos'
    | '/cadastro'
    | '/checkout'
    | '/doencas'
    | '/login'
    | '/loja'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/seja-distribuidor'
    | '/alerts'
    | '/analytics'
    | '/commissions'
    | '/copilot'
    | '/insights'
    | '/marketing'
    | '/network'
    | '/plans'
    | '/settings'
    | '/system'
    | '/wallets'
    | '/busca-produtos/$slug'
    | '/doencas/$slug'
    | '/loja/$slug'
    | '/office/copilot'
    | '/office/downloads'
    | '/office/finance'
    | '/office/network'
    | '/office/orders'
    | '/office/plan'
    | '/office/profile'
    | '/office/reports'
    | '/office/store'
    | '/office/verification'
    | '/produto/$id'
    | '/seja-distribuidor/$slug'
    | '/office'
    | '/customers/$id'
    | '/auth/invite/$token'
    | '/customers'
    | '/orders'
    | '/products'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/_app'
    | '/ativacao'
    | '/busca-produtos'
    | '/cadastro'
    | '/checkout'
    | '/doencas'
    | '/login'
    | '/loja'
    | '/office'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/seja-distribuidor'
    | '/_app/alerts'
    | '/_app/analytics'
    | '/_app/commissions'
    | '/_app/copilot'
    | '/_app/insights'
    | '/_app/marketing'
    | '/_app/network'
    | '/_app/plans'
    | '/_app/settings'
    | '/_app/system'
    | '/_app/wallets'
    | '/busca-produtos/$slug'
    | '/doencas/$slug'
    | '/loja/$slug'
    | '/office/copilot'
    | '/office/downloads'
    | '/office/finance'
    | '/office/network'
    | '/office/orders'
    | '/office/plan'
    | '/office/profile'
    | '/office/reports'
    | '/office/store'
    | '/office/verification'
    | '/produto/$id'
    | '/seja-distribuidor/$slug'
    | '/office/'
    | '/_app/customers/$id'
    | '/auth/invite/$token'
    | '/_app/customers/'
    | '/_app/orders/'
    | '/_app/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  AppRoute: typeof AppRouteWithChildren
  AtivacaoRoute: typeof AtivacaoRoute
  BuscaProdutosRoute: typeof BuscaProdutosRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  CheckoutRoute: typeof CheckoutRoute
  DoencasRoute: typeof DoencasRouteWithChildren
  LoginRoute: typeof LoginRoute
  LojaRoute: typeof LojaRouteWithChildren
  OfficeRoute: typeof OfficeRouteWithChildren
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  SejaDistribuidorRoute: typeof SejaDistribuidorRouteWithChildren
  ProdutoIdRoute: typeof ProdutoIdRoute
  AuthInviteTokenRoute: typeof AuthInviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/seja-distribuidor': {
      id: '/seja-distribuidor'
      path: '/seja-distribuidor'
      fullPath: '/seja-distribuidor'
      preLoaderRoute: typeof SejaDistribuidorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office': {
      id: '/office'
      path: '/office'
      fullPath: '/office'
      preLoaderRoute: typeof OfficeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja': {
      id: '/loja'
      path: '/loja'
      fullPath: '/loja'
      preLoaderRoute: typeof LojaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doencas': {
      id: '/doencas'
      path: '/doencas'
      fullPath: '/doencas'
      preLoaderRoute: typeof DoencasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/busca-produtos': {
      id: '/busca-produtos'
      path: '/busca-produtos'
      fullPath: '/busca-produtos'
      preLoaderRoute: typeof BuscaProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ativacao': {
      id: '/ativacao'
      path: '/ativacao'
      fullPath: '/ativacao'
      preLoaderRoute: typeof AtivacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office/': {
      id: '/office/'
      path: '/'
      fullPath: '/office/'
      preLoaderRoute: typeof OfficeIndexRouteImport
      parentRoute: typeof OfficeRoute
    }
    '/seja-distribuidor/$slug': {
      id: '/seja-distribuidor/$slug'
      path: '/$slug'
      fullPath: '/seja-distribuidor/$slug'
      preLoaderRoute: typeof SejaDistribuidorSlugRouteImport
      parentRoute: typeof SejaDistribuidorRoute
    }
    '/produto/$id': {
      id: '/produto/$id'
      path: '/produto/$id'
      fullPath: '/produto/$id'
      preLoaderRoute: typeof ProdutoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office/verification': {
      id: '/office/verification'
      path: '/verification'
      fullPath: '/office/verification'
      preLoaderRoute: typeof OfficeVerificationRouteImport
      parentRoute: typeof OfficeRoute
    }
    '/office/store': {
      id: '/office/store'
      path: '/store'
      fullPath: '/office/store'
      preLoaderRoute: typeof OfficeStoreRouteImport
      parentRoute: typeof OfficeRoute
    }
    '/office/reports': {
      id: '/office/reports'
      path: '/reports'
      fullPath: '/office/reports'
      preLoaderRoute: typeof OfficeReportsRouteImport
      parentRoute: typeof OfficeRoute
    }
    '/office/profile': {
      id: '/office/profile'
      path: '/profile'
      fullPath: '/office/profile'
      preLoaderRoute: typeof OfficeProfileRouteImport
      parentRoute: typeof OfficeRoute
    }
    '/office/plan': {
      id: '/office/plan'
      path: '/plan'
      fullPath: '/office/plan'
      preLoaderRoute: typeof OfficePlanRouteImport
      parentRoute: typeof OfficeRoute
    }
    '/office/orders': {
      id: '/office/orders'
      path: '/orders'
      fullPath: '/office/orders'
      preLoaderRoute: typeof OfficeOrdersRouteImport
      parentRoute: typeof OfficeRoute
    }
    '/office/network': {
      id: '/office/network'
      path: '/network'
      fullPath: '/office/network'
      preLoaderRoute: typeof OfficeNetworkRouteImport
      parentRoute: typeof OfficeRoute
    }
    '/office/finance': {
      id: '/office/finance'
      path: '/finance'
      fullPath: '/office/finance'
      preLoaderRoute: typeof OfficeFinanceRouteImport
      parentRoute: typeof OfficeRoute
    }
    '/office/downloads': {
      id: '/office/downloads'
      path: '/downloads'
      fullPath: '/office/downloads'
      preLoaderRoute: typeof OfficeDownloadsRouteImport
      parentRoute: typeof OfficeRoute
    }
    '/office/copilot': {
      id: '/office/copilot'
      path: '/copilot'
      fullPath: '/office/copilot'
      preLoaderRoute: typeof OfficeCopilotRouteImport
      parentRoute: typeof OfficeRoute
    }
    '/loja/$slug': {
      id: '/loja/$slug'
      path: '/$slug'
      fullPath: '/loja/$slug'
      preLoaderRoute: typeof LojaSlugRouteImport
      parentRoute: typeof LojaRoute
    }
    '/doencas/$slug': {
      id: '/doencas/$slug'
      path: '/$slug'
      fullPath: '/doencas/$slug'
      preLoaderRoute: typeof DoencasSlugRouteImport
      parentRoute: typeof DoencasRoute
    }
    '/busca-produtos/$slug': {
      id: '/busca-produtos/$slug'
      path: '/$slug'
      fullPath: '/busca-produtos/$slug'
      preLoaderRoute: typeof BuscaProdutosSlugRouteImport
      parentRoute: typeof BuscaProdutosRoute
    }
    '/_app/wallets': {
      id: '/_app/wallets'
      path: '/wallets'
      fullPath: '/wallets'
      preLoaderRoute: typeof AppWalletsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/system': {
      id: '/_app/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof AppSystemRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plans': {
      id: '/_app/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof AppPlansRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/network': {
      id: '/_app/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof AppNetworkRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/marketing': {
      id: '/_app/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof AppMarketingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/insights': {
      id: '/_app/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AppInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/copilot': {
      id: '/_app/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof AppCopilotRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/commissions': {
      id: '/_app/commissions'
      path: '/commissions'
      fullPath: '/commissions'
      preLoaderRoute: typeof AppCommissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alerts': {
      id: '/_app/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products/': {
      id: '/_app/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AppProductsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders/': {
      id: '/_app/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof AppOrdersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers/': {
      id: '/_app/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AppCustomersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/invite/$token': {
      id: '/auth/invite/$token'
      path: '/auth/invite/$token'
      fullPath: '/auth/invite/$token'
      preLoaderRoute: typeof AuthInviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/customers/$id': {
      id: '/_app/customers/$id'
      path: '/customers/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof AppCustomersIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAlertsRoute: typeof AppAlertsRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppCommissionsRoute: typeof AppCommissionsRoute
  AppCopilotRoute: typeof AppCopilotRoute
  AppInsightsRoute: typeof AppInsightsRoute
  AppMarketingRoute: typeof AppMarketingRoute
  AppNetworkRoute: typeof AppNetworkRoute
  AppPlansRoute: typeof AppPlansRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSystemRoute: typeof AppSystemRoute
  AppWalletsRoute: typeof AppWalletsRoute
  AppCustomersIdRoute: typeof AppCustomersIdRoute
  AppCustomersIndexRoute: typeof AppCustomersIndexRoute
  AppOrdersIndexRoute: typeof AppOrdersIndexRoute
  AppProductsIndexRoute: typeof AppProductsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlertsRoute: AppAlertsRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppCommissionsRoute: AppCommissionsRoute,
  AppCopilotRoute: AppCopilotRoute,
  AppInsightsRoute: AppInsightsRoute,
  AppMarketingRoute: AppMarketingRoute,
  AppNetworkRoute: AppNetworkRoute,
  AppPlansRoute: AppPlansRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSystemRoute: AppSystemRoute,
  AppWalletsRoute: AppWalletsRoute,
  AppCustomersIdRoute: AppCustomersIdRoute,
  AppCustomersIndexRoute: AppCustomersIndexRoute,
  AppOrdersIndexRoute: AppOrdersIndexRoute,
  AppProductsIndexRoute: AppProductsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface BuscaProdutosRouteChildren {
  BuscaProdutosSlugRoute: typeof BuscaProdutosSlugRoute
}

const BuscaProdutosRouteChildren: BuscaProdutosRouteChildren = {
  BuscaProdutosSlugRoute: BuscaProdutosSlugRoute,
}

const BuscaProdutosRouteWithChildren = BuscaProdutosRoute._addFileChildren(
  BuscaProdutosRouteChildren,
)

interface DoencasRouteChildren {
  DoencasSlugRoute: typeof DoencasSlugRoute
}

const DoencasRouteChildren: DoencasRouteChildren = {
  DoencasSlugRoute: DoencasSlugRoute,
}

const DoencasRouteWithChildren =
  DoencasRoute._addFileChildren(DoencasRouteChildren)

interface LojaRouteChildren {
  LojaSlugRoute: typeof LojaSlugRoute
}

const LojaRouteChildren: LojaRouteChildren = {
  LojaSlugRoute: LojaSlugRoute,
}

const LojaRouteWithChildren = LojaRoute._addFileChildren(LojaRouteChildren)

interface OfficeRouteChildren {
  OfficeCopilotRoute: typeof OfficeCopilotRoute
  OfficeDownloadsRoute: typeof OfficeDownloadsRoute
  OfficeFinanceRoute: typeof OfficeFinanceRoute
  OfficeNetworkRoute: typeof OfficeNetworkRoute
  OfficeOrdersRoute: typeof OfficeOrdersRoute
  OfficePlanRoute: typeof OfficePlanRoute
  OfficeProfileRoute: typeof OfficeProfileRoute
  OfficeReportsRoute: typeof OfficeReportsRoute
  OfficeStoreRoute: typeof OfficeStoreRoute
  OfficeVerificationRoute: typeof OfficeVerificationRoute
  OfficeIndexRoute: typeof OfficeIndexRoute
}

const OfficeRouteChildren: OfficeRouteChildren = {
  OfficeCopilotRoute: OfficeCopilotRoute,
  OfficeDownloadsRoute: OfficeDownloadsRoute,
  OfficeFinanceRoute: OfficeFinanceRoute,
  OfficeNetworkRoute: OfficeNetworkRoute,
  OfficeOrdersRoute: OfficeOrdersRoute,
  OfficePlanRoute: OfficePlanRoute,
  OfficeProfileRoute: OfficeProfileRoute,
  OfficeReportsRoute: OfficeReportsRoute,
  OfficeStoreRoute: OfficeStoreRoute,
  OfficeVerificationRoute: OfficeVerificationRoute,
  OfficeIndexRoute: OfficeIndexRoute,
}

const OfficeRouteWithChildren =
  OfficeRoute._addFileChildren(OfficeRouteChildren)

interface SejaDistribuidorRouteChildren {
  SejaDistribuidorSlugRoute: typeof SejaDistribuidorSlugRoute
}

const SejaDistribuidorRouteChildren: SejaDistribuidorRouteChildren = {
  SejaDistribuidorSlugRoute: SejaDistribuidorSlugRoute,
}

const SejaDistribuidorRouteWithChildren =
  SejaDistribuidorRoute._addFileChildren(SejaDistribuidorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  AppRoute: AppRouteWithChildren,
  AtivacaoRoute: AtivacaoRoute,
  BuscaProdutosRoute: BuscaProdutosRouteWithChildren,
  CadastroRoute: CadastroRoute,
  CheckoutRoute: CheckoutRoute,
  DoencasRoute: DoencasRouteWithChildren,
  LoginRoute: LoginRoute,
  LojaRoute: LojaRouteWithChildren,
  OfficeRoute: OfficeRouteWithChildren,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  SejaDistribuidorRoute: SejaDistribuidorRouteWithChildren,
  ProdutoIdRoute: ProdutoIdRoute,
  AuthInviteTokenRoute: AuthInviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
