-- Current schema snapshot for project isjsydhuqurneswstlyx
-- Generated from the live database state on 2026-05-29.
-- This file documents the observed schema for reference in version control.
-- No DDL is included here because the target database already contains these tables.
--
-- Public tables currently present:
-- admin_users
-- audit_log
-- campaign_intelligence
-- campaigns
-- chatwoot_conversations
-- chatwoot_messages
-- customer_events
-- customer_metrics
-- customer_network_metrics
-- customer_plans
-- customer_predictions
-- customer_product_affinities
-- customer_scores
-- customers
-- leads
-- marketing_links
-- network_relationships
-- order_items
-- order_items_normalized
-- orders
-- payments
-- plan_bonuses
-- plans
-- product_affinities
-- product_metrics
-- product_variants
-- products
-- profiles
-- qualifications
-- shipments
-- workspace_settings
